
name: magoo_player
description: IPTV player app (Xtream + M3U)
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  better_player: ^0.0.81

flutter:
  uses-material-design: true
